version: '3.8'

services:
  redis:
    image: redis:7.2.3
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data
    env_file: ./.env
  worker:
    build:
      context: .
    hostname: worker
    container_name: worker
    command: celery -A worker.tasks:worker worker -l info --pool=solo
    depends_on:
      - redis
    volumes:
      - ./media:/app/media
  flower:
    build:
      context: .
    hostname: flower
    container_name: flower
    command: celery -A worker.tasks:worker flower
    ports:
      - 5555:5555
    depends_on:
      - worker
    volumes:
      - ./media:/app/media
  db:
    image: postgres:16.1
    hostname: db
    container_name: db
    volumes:
      - database_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file: ./.env
  web:
    build:
      context: .
    hostname: web
    container_name: web
    env_file: ./.env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    command: bash -c "python main.py"
  nginx:
    image: nginx:1.25.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - web
volumes:
  database_volume:
  redis_volume:
  static_volume:
  media_volume:
